---
title: "Reading data from the web"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## strings and regex

```{r}
string_vec = c("my", "name", "is", "jeff")

#detect a particular pattern (str_detect)
str_detect(string_vec, "jeff")
str_detect(string_vec, "e") #doesn't have to match whole pattern
str_detect(string_vec, "Jeff")
```

```{r replace}
string_vec = c("my", "name", "is", "jeff")
str_replace(string_vec, "jeff", "Jeff")
```

```{r new string vector}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun",
  "it will be fun, i think"
)

str_detect(string_vec, "i think")
# detect strings that start w/ i think
str_detect(string_vec, "^i think") #^ = starts with
str_detect(string_vec, "i think$") #$ = ends with
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo George",
  "BUSH -- LIVE IN CONCERT!!"
)

str_detect(string_vec, "bush")
str_detect(string_vec, "Bush")
str_detect(string_vec, "[Bb]ush") #lower or uppercase B
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

# choose ranges
str_detect(string_vec, "^[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
)

str_detect(string_vec, "7.11") #. = special char that matches anything
str_detect(string_vec, "7\\.11") #interpret . as actual . w/ \\
```

## Factors

```{r}
factor_vec = factor(c("male", "male", "female", "female"))

as.numeric(factor_vec)
```

what happens if i relevel?
```{r}
factor_vec = fct_relevel(factor_vec, "male") # male = first or reference
as.numeric(factor_vec)
```

## NSDUH

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

tabl_marj =
  read_html(url) %>% 
  html_nodes(css = "table") %>% 
  first() %>%  #extract first table, also available 'nth' 'last'
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()
```


